---
title: "Documentation"
author: "AM"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

This app aims at showing how inclusion and exclusion of regressors impacts the final prediction. 

The dataset *airquality* has been used and the variable *Ozone* is fitted with the variables *Solar.R*, *Temp* and *Wind*. The user can chose via checkboxs which and how many of the three regressors should be included in the fitting procedure. The resulting formula, plot of original and predicted *Ozone* values vs *Solar.R* values, table of coefficients and R squared coefficients are displayed.

## Instructions

From the left-hand side panel *"Build your model!"* tick one or more of the checkboxes. When you are satisfied with the selection, press the button *Submit*.

On the main panel on the results from the built model are displayed.

## How it works

The input checkboxes are used to build up a string containing a formula which is used to perform a linear regression. The outputs of the *Shyniserver* function are the formula, the model itself (from which R squared and table of coefficients are extracted and displayed), and the set of values predicted by the model (used to display the plot). 

Selection of no variables leads the app to display a main panel with only titles. Error messages where prevented by the use of *req(isThruthy(...))* commands.

## Further developments

This is the simplest version possible. Among the many feasible improvements, the following would be the most immediate:

1. Possibility to add interaction terms in the building up of the formula. 

1. Choice to include or exclude the variables *Month* and *Day* in the process, either by simple inclusion as regressors, or as grouping variables, to highlight the difference it makes.

2. Output plot displaying the *Ozone* values (original and predicted) against a variable of choice.

3. Possibility to use a 3D plot instead of the currently used 2D plot.